name = "andre-youth-api"
main = "src/index.js"
compatibility_date = "2026-08-28"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "andre-youth-db"
database_id = "6073f897-1c01-4d74-8e85-e4df6758a2a1"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ply999"
